language: go
os:
  - linux
  - osx
go:
  - 1.2
  - 1.3
  - 1.4
  - tip
matrix:
  include:
    - os: linux
      before_install: sudo apt-get install isc-dhcp-client
install:
  - go get "github.com/codegangsta/cli"
  - go install "./cmd/dns-client-conf"

script:
  - dns-client-conf show
  - sudo $HOME/gopath/bin/dns-client-conf --debug=true add 8.8.8.8 8.8.4.4
  - dns-client-conf show
  - sudo $HOME/gopath/bin/dns-client-conf dhcp
  - dns-client-conf show
