language: go
go:
  - 1.2
  - 1.3
  - 1.4
  - tip
install:
  - go get "github.com/codegangsta/cli"
  - go get -v
  - go build -v
  - go install

script:
  - dns-client-conf --debug=true add 8.8.8.8 8.8.4.4
